header:
  version: 14

local_conf_header:
  misc: |
    PACKAGE_CLASSES = "package_ipk"
    USER_CLASSES ?= "buildstats"
    BB_GENERATE_MIRROR_TARBALLS = "1"
    INHERIT += "image-buildinfo"
    IMAGE_BUILDINFO_VARS:append = " DATETIME DISTRO_NAME IMAGE_BASENAME MACHINE TUNE_PKGARCH"
    IMAGE_BUILDINFO_VARS:append = " MACHINE_FEATURES DISTRO_FEATURES COMMON_FEATURES IMAGE_FEATURES"
    IMAGE_BUILDINFO_VARS:append = " TUNE_FEATURES TARGET_FPU"
